# Uncomment the next line to define a global platform for your project
platform :ios, ‘10.0’

target 'appLPS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'



  target 'appLPSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'appLPSUITests' do
    # Pods for testing
  end

end
